<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Direct2dDemo.Direct2D\Direct2dDemo.Direct2D.csproj" />
    <ProjectReference Include="..\Direct2dDemo.GDI\Direct2dDemo.GDI.csproj" />
    <ProjectReference Include="..\Direct2dDemo.Shared\Direct2dDemo.Shared.csproj" />
  </ItemGroup>

</Project>
